// <auto-generated />
using IndeedJobs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IndeedJobs.Migrations
{
    [DbContext(typeof(IndeedJobsContext))]
    partial class IndeedJobsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("IndeedJobs.Models.Job", b =>
                {
                    b.Property<int>("Position")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CompanyLogoUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyRating")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyReviewLink")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CompanyReviews")
                        .HasColumnType("int");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("JobLocation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("JobUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MultipleHiring")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("NextPage")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int");

                    b.Property<string>("Salary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UrgentlyHiring")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Position");

                    b.ToTable("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
